### ISSUE TITLE
Missing parameter: code

### ISSUE THREAD

**Issue by bahnuhr** [TA2k/ioBroker.bosch-ebike#27]
Im log kommt:
`bosch-ebike.0
2024-11-23 19:10:42.624	error	{"error":"invalid_request","error_description":"Missing parameter: code"}
bosch-ebike.0
2024-11-23 19:10:42.624	error	AxiosError: Request failed with status code 400`

vgl. auch Forum:
https://forum.iobroker.net/topic/55902/test-adapter-bosch-ebik-connect-flow/94?_=1732344774071

Instanz bleibt gelb.

**Comment by TA2k** [comment]
bike connect or flow?

**Comment by Madcatmichl** [comment]
Bei mir im Flow, habe das gleich Problem.

**Comment by bahnuhr** [comment]
Bei mir auch flow

**Comment by TA2k** [comment]
fixed with 0.1.8

**Comment by Madcatmichl** [comment]
Danke für den Fix :)
